version: 5.0.0
variant: default
logo: img/jelee/logo.png
head:
  favicon: img/jelee/favicon.ico
  manifest:
    name:
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ''
        sizes: ''
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ''
  rss:
navbar:
  menu:
    # Home: /
    Steady: /steady
    HTML/CSS: /categories/HTML-CSS
    JavaScript: /categories/JavaScript
    Lab: /categories/Lab
    Option: /categories/Option
    Archives: /archives
    # Categories: /categories
  links:
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/jelee603
footer:
  links:
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: false
  update_time: false
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
comment:
  type: false
  shortname: ''
donates:
  - type: none
    url: ''
  - type: none
    qrcode: ''
  - type: none
    url: ''
  - type: none
    url: ''
  - type: none
    business: ''
    currency_code: USD
  - type: none
    qrcode: ''
share:
  type: none
  install_url: ''
sidebar:
  left:
    sticky: false
  right:
    sticky: true
widgets:
  - position: none
    type: profile
    author: Your name
    author_title: Your title
    location: Your location
    avatar:
    avatar_rounded: false
    gravatar:
    follow_link: https://github.com/ppoffice
    social_links:
  - position: right
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: none
    type: links
    links:
      Hexo: https://hexo.io
      Bulma: https://bulma.io
  - position: none
    type: categories
  - position: right
    type: recent_posts
  - position: none
    type: archives
  - position: none
    type: tags
  - position: none
    type: subscribe_email
    description:
    feedburner_id: ''
  - position: right
    type: adsense
    client_id: 'ca-pub-7250093750072260'
    slot_id: '4932064801'
  - position: none
    type: followit
    description:
    action_url: ''
    verification_code: ''
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  bing_webmaster:
    tracking_id:
  busuanzi: false
  cnzz:
    id:
    web_id:
  #   cookie_consent:
  #     type: none
  #     theme: edgeless
  #     static: false
  #     position: bottom-left
  #     policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
